var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/services/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__65c97167._.js")
R.c("server/chunks/ssr/_d25179f9._.js")
R.c("server/chunks/ssr/_75a500e5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f1c3be06._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c6bcf5a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/node_modules_9c78f052._.js")
R.c("server/chunks/ssr/[root-of-the-server]__27825a35._.js")
R.c("server/chunks/ssr/app_not-found_tsx_339d4b53._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_services_page_actions_996e348c.js")
R.m(99905)
module.exports=R.m(99905).exports
